# Generated by Django 3.0.5 on 2020-04-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200428_0709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
