# Generated by Django 3.0.5 on 2020-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200423_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
