# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200428_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='interested_items',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='author',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
