# Generated by Django 3.0.5 on 2020-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200428_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='media/Web_post.png', null=True, upload_to=''),
        ),
    ]
