# Generated by Django 3.0.5 on 2020-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200428_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
