# Generated by Django 3.0.5 on 2020-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200429_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
