# Generated by Django 3.0.5 on 2020-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200430_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to='profile-pics'),
        ),
    ]
